#!/bin/sh
filesToMakePrettier=$(git diff --cached --name-only --diff-filter=ACM "*.js" "*.ts" "*.jsx" "*.tsx" "*.css" "*.scss" | tr '\n' ' ')
[ -z "$filesToMakePrettier" ] && exit 0

# Prettify staged files
echo "$filesToMakePrettier" | xargs ./node_modules/.bin/prettier --write

# Add back the modified/prettified files to staging
echo "$filesToMakePrettier" | xargs git add

exit 0